---
- name: Disable Password Authentication
  lineinfile:
    line: PasswordAuthentication no
    regexp: ^PasswordAuthentication
    path: /etc/ssh/sshd_config

- name: Disable root login
  lineinfile:
    line: PermitRootLogin no
    regexp: ^PermitRootLogin
    path: /etc/ssh/sshd_config

- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: true
