---
- name: Create a database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: test_database
    state: present
    login_user: root
    login_password: ''
- name: Add sample data
  copy:
    src: ../templates/test.sql
    dest: /tmp/test.sql
- name: Insert sample data
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: test_database
    state: import
    target: /tmp/test.sql
    login_user: root
    login_password: ''
