---
- name: Create a database user named tester
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: ''
    name: tester
    password: ''
    priv: 'test_database.*:ALL'
    state: present
