---
- name: Install required packages for the LAMP
  apt:
    pkg:
    - apache2
    - mariadb-server
    - php
    - libapache2-mod-php
    - php-mysql
    state: latest

- name: mysql_secure_installation
  expect:
    command: mysql_secure_installation
    responses:
      'Enter current password for root': ''
      'Set root password?': 'n'
      'Change the root password?': 'n'
      'Remove anonymous users?': 'y'
      'Disallow root login remotely?': 'y'
      'Remove test database and access to it?': 'y'
      'Reload privilege tables now?': 'y'

